// -*- C++ -*- generated by wxGlade 0.6.5 on Mon Jun 04 08:30:53 2012 from "C:\dpo\tools\scripts\cta\cta.wxg"

#include <wx/wx.h>
#include <wx/image.h>
#include <vector>
#include <string>
#include "ImportSelectionDlg.h"
#include "EnvVarVect.h"
#include "wx_ids.h"

#ifndef IMPORTDLG_H
#define IMPORTDLG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class ImportDlg: public wxDialog {
public:
    // begin wxGlade: ImportDlg::ids
    // end wxGlade

    ImportDlg(EnvVarVect * user,
                EnvVarVect * system,
                wxWindow* parent,
                int id,
                const wxString& title,
                const wxPoint& pos=wxDefaultPosition,
                const wxSize& size=wxDefaultSize,
                long style=wxDEFAULT_DIALOG_STYLE);
    void set_files(std::vector<std::string> & vect);

private:
    // begin wxGlade: ImportDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ImportDlg::attributes
    wxStaticText* label_1;
    wxListBox* list_box_backup_files_;
    wxButton* button_next_;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_button_next(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_file_select(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    EnvVarVect * env_vars_user_;
    EnvVarVect * env_vars_system_;
}; // wxGlade: end class



#endif // IMPORTDLG_H
