// -*- C++ -*- generated by wxGlade 0.6.5 on Mon Jun 04 08:30:53 2012 from "C:\dpo\tools\scripts\cta\cta.wxg"

#include "ImportDlg.h"

// begin wxGlade: ::extracode

// end wxGlade



ImportDlg::ImportDlg(EnvVarVect * user,
                        EnvVarVect * system,
                        wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
    , env_vars_user_(user)
    , env_vars_system_(system)
{
    // begin wxGlade: ImportDlg::ImportDlg
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Select a file and click 'Next...'"));
    const wxString *list_box_backup_files__choices = NULL;
    list_box_backup_files_ = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, list_box_backup_files__choices, wxLB_SINGLE);
    button_next_ = new wxButton(this, wxID_HIGHEST + wxID_button_next, wxT("Next..."));

    set_properties();
    do_layout();
    // end wxGlade
}

BEGIN_EVENT_TABLE(ImportDlg, wxDialog)
    // begin wxGlade: ImportDlg::event_table
    EVT_LISTBOX(wxID_ANY, ImportDlg::on_file_select)
    EVT_BUTTON(wxID_HIGHEST + wxID_button_next, ImportDlg::on_button_next)
    // end wxGlade
END_EVENT_TABLE();


void ImportDlg::on_file_select(wxCommandEvent &event)
{
    button_next_->Enable(true);
}

void ImportDlg::on_button_next(wxCommandEvent &event)
{
    std::string backup_file_to_read = list_box_backup_files_->GetStringSelection().ToStdString();

    ImportSelectionDlg dlg(env_vars_user_,
                            env_vars_system_,
                            this, -1, "Available environment variables");

    if (!dlg.read_file(backup_file_to_read))
    {
        wxString msg;
        msg.Printf("Can't read file: %s.",
                    backup_file_to_read.c_str());
        wxMessageBox(msg.c_str(),
                    "Importing environment variables",
                    wxOK | wxICON_ERROR);
    }
    else
    {
        dlg.ShowModal();
        this->Destroy();
    }
}


// wxGlade: add ImportDlg event handlers


void ImportDlg::set_properties()
{
    // begin wxGlade: ImportDlg::set_properties
    SetTitle(wxT("Import environment variables"));
    SetSize(wxSize(643, 480));
    button_next_->Enable(false);
    // end wxGlade
}


void ImportDlg::do_layout()
{
    // begin wxGlade: ImportDlg::do_layout
    wxBoxSizer* sizer_19 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_20 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_21 = new wxBoxSizer(wxHORIZONTAL);
    sizer_20->Add(label_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    sizer_21->Add(list_box_backup_files_, 3, wxEXPAND, 0);
    sizer_21->Add(button_next_, 0, wxALL|wxALIGN_CENTER_VERTICAL, 5);
    sizer_20->Add(sizer_21, 1, wxEXPAND, 0);
    sizer_19->Add(sizer_20, 1, wxEXPAND, 0);
    SetSizer(sizer_19);
    Layout();
    // end wxGlade
}


void ImportDlg::set_files(std::vector<std::string> & vect)
{
    std::vector<std::string>::iterator it;
    for (it = vect.begin(); it != vect.end(); it++)
    {
        list_box_backup_files_->Append(*it);
    }
}

