// -*- C++ -*- generated by wxGlade 0.6.5 on Mon Jun 04 08:30:53 2012 from "C:\dpo\tools\scripts\cta\cta.wxg"

#include "InfoDlg.h"
#include "Version.h"

// begin wxGlade: ::extracode

// end wxGlade


InfoDlg::InfoDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
{
    // begin wxGlade: InfoDlg::InfoDlg
    text_ctrl_info_ = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY|wxHSCROLL);

    set_properties();
    do_layout();
    // end wxGlade
}


void InfoDlg::set_properties()
{
    // begin wxGlade: InfoDlg::set_properties
    SetTitle(wxT("About"));
    text_ctrl_info_->SetMinSize(wxSize(640,480));
    // end wxGlade

    text_ctrl_info_->SetValue(
        "CTA  (Version " CTA_VERSION ")\n\n"
        "    CTA is another Windows environment variables editor. After some\n"
        "    researches, I found these:\n"
        "        - sysdm.cpl (the one that Windows provides)\n"
        "        - http://silvermace.com/weve\n"
        "        - http://sourceforge.net/projects/yawee\n"
        "        - http://sourceforge.net/projects/winenvedit\n"
        "        - http://www.rapidee.com\n\n"
        "    CTA solves a problem not solved by the ones listed above.\n"
        "    See WINDOWS ENVIRONMENT VARIABLE PROBLEM section.\n\n"
        "    It is also a better GUI than sysdm.cpl.\n\n"
        "LICENSE\n\n"
        "    ==========================================================\n"
        "    Copyright (C) 2012 Hubert Talbot. All rights reserved.\n"
        "    ==========================================================\n\n"
        "    CTA is licensed under the GNU General Public License.\n\n"
        "    CTA is free software: you can redistribute it and/or modify\n"
        "    it under the terms of the GNU General Public License as published by\n"
        "    the Free Software Foundation, either version 3 of the License, or\n"
        "    (at your option) any later version.\n\n"
        "    CTA is distributed in the hope that it will be useful,\n"
        "    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
        "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
        "    GNU General Public License for more details.\n\n"

        "    You should have received a copy of the GNU General Public License\n"
        "    along with CTA.  If not, see http://www.gnu.org/licenses/\n"
        "    ==========================================================\n\n"
        "WINDOWS ENVIRONMENT VARIABLE PROBLEM\n\n"
        "    Once, I tried to build ACE/TAO/CIAO (http://www.cs.wustl.edu/~schmidt/) in Windows.\n\n"
        "    I built ACE and TAO successfully but failed with CIAO.\n\n"
        "    To build ACE/TAO/CIAO, we can define environment variables ACE_ROOT, TAO_ROOT and CIAO_ROOT.\n"
        "    TAO_ROOT is defined as ACE_ROOT: TAO_ROOT=%ACE_ROOT%\\TAO and\n"
        "    CIAO_ROOT is defined as TAO_ROOT: CIAO_ROOT=%TAO_ROOT%\\CIAO.\n\n"
        "    The problem is that Windows does not expand environment variables properly when level of nestings exceeds two.\n"
        "    In this case, Windows can resolve TAO_ROOT because it depends on ACE_ROOT only. For CIAO_ROOT, Windows\n"
        "    is unable to resolve CIAO_ROOT because it depends on TAO_ROOT that in turns, depends on ACE_ROOT. Then,\n"
        "    to be able to build CIAO, I had to define CIAO_ROOT as its actual path, not really convenient...\n\n"
        "    CTA solves this problem.\n\n"
        "NAME\n\n"
        "    The name CTA is based on environment variables that originally highlighted the problem for me;\n"
        "    that is to say, the environment variables involved while compiling ACE/TAO/CIAO.\n\n"
        "    The letters CTA represent:\n"
        "         C: CIAO\n"
        "         T: TAO\n"
        "         A: ACE\n\n"
        "LOGO\n\n"
        "    The logo is composed of three circles.\n"
        "    - The inner one corresponds to ACE\n"
        "    - The one in the middle corresponds to TAO. TAO is defined as ACE.\n"
        "    - The outer one corresponds to CIAO. CIAO is defined as TAO.\n\n"
        "NOTE\n\n"
        "    If you need to define environment variables according to others, this\n"
        "    application is for you.\n\n"
        "    If you need to define environment variables according to others, avoid\n"
        "    using tools like the one provided by Windows (sysdm.cpl) because\n"
        "    they don't do the job correctly. You will have to fix the problem with CTA anyway.\n\n"
        "    Despite this program addresses some problems, another issue remains.\n"
        "    When we set an environment variable value for which the length exceeds 2048 \n"
        "    (depending on the version of Windows), we have to logout/login (at least, else reboot) for this\n"
        "    change to take effect. If someone knows how to set an environment variable \n"
        "    value with a length exceeding 2048 without having to logout/login, please let me know.\n"
        "    Note also that from CTA, the maximum length of an environment variable value we can enter is 260.\n\n\n"
        "  hubert.talbot64@gmail.com \n\n"
    );
}


void InfoDlg::do_layout()
{
    // begin wxGlade: InfoDlg::do_layout
    wxBoxSizer* sizer_16 = new wxBoxSizer(wxVERTICAL);
    sizer_16->Add(text_ctrl_info_, 1, wxEXPAND, 0);
    SetSizer(sizer_16);
    sizer_16->Fit(this);
    Layout();
    // end wxGlade
}



