// -*- C++ -*- generated by wxGlade 0.6.5 on Mon Jun 04 08:30:53 2012 from "C:\dpo\tools\scripts\cta\cta.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef INFODLG_H
#define INFODLG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class InfoDlg: public wxDialog {
public:
    // begin wxGlade: InfoDlg::ids
    // end wxGlade

    InfoDlg(wxWindow* parent,
            int id,
            const wxString& title,
            const wxPoint& pos=wxDefaultPosition,
            const wxSize& size=wxDefaultSize,
            long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);

private:
    // begin wxGlade: InfoDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: InfoDlg::attributes
    wxTextCtrl* text_ctrl_info_;
    // end wxGlade
}; // wxGlade: end class


#endif // INFODLG_H


