// -*- C++ -*- generated by wxGlade 0.6.5 on Mon Jun 04 08:30:53 2012 from "C:\dpo\tools\scripts\cta\cta.wxg"

#include "NewVarDlg.h"

// begin wxGlade: ::extracode

// end wxGlade


NewVarDlg::NewVarDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
{
    // begin wxGlade: NewVarDlg::NewVarDlg
    label_new_env_var_ = new wxStaticText(this, wxID_ANY, wxT("New environment variable:"));
    text_ctrl_new_env_var_ = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_value_ = new wxStaticText(this, wxID_ANY, wxT("Value:"));
    text_ctrl_value_ = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_ok_ = new wxButton(this, wxID_HIGHEST + wxID_button_ok, wxT("Ok"));
    button_cancel_ = new wxButton(this, wxID_HIGHEST + wxID_button_cancel, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(NewVarDlg, wxDialog)
    // begin wxGlade: NewVarDlg::event_table
    EVT_BUTTON(wxID_HIGHEST + wxID_button_ok, NewVarDlg::on_ok)
    EVT_BUTTON(wxID_HIGHEST + wxID_button_cancel, NewVarDlg::on_cancel)
    // end wxGlade
END_EVENT_TABLE();


void NewVarDlg::on_ok(wxCommandEvent &event)
{
    EndModal(wxID_OK);
}


void NewVarDlg::on_cancel(wxCommandEvent &event)
{
    EndModal(wxID_CANCEL);
}


// wxGlade: add NewVarDlg event handlers


void NewVarDlg::set_properties()
{
    // begin wxGlade: NewVarDlg::set_properties
    SetTitle(wxT("New environment variable"));
    SetSize(wxSize(600, 175));
    // end wxGlade
}


void NewVarDlg::do_layout()
{
    // begin wxGlade: NewVarDlg::do_layout
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_13 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_11 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_14 = new wxBoxSizer(wxHORIZONTAL);
    sizer_14->Add(label_new_env_var_, 0, 0, 0);
    sizer_14->Add(text_ctrl_new_env_var_, 1, 0, 0);
    sizer_13->Add(sizer_14, 0, wxALL|wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 5);
    sizer_11->Add(label_value_, 0, 0, 0);
    sizer_11->Add(text_ctrl_value_, 1, 0, 0);
    sizer_13->Add(sizer_11, 0, wxALL|wxEXPAND|wxALIGN_CENTER_HORIZONTAL, 5);
    sizer_10->Add(sizer_13, 1, wxEXPAND, 0);
    sizer_12->Add(button_ok_, 0, wxALL, 5);
    sizer_12->Add(button_cancel_, 0, wxALL, 5);
    sizer_10->Add(sizer_12, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 10);
    SetSizer(sizer_10);
    Layout();
    // end wxGlade
}
